eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: eureka/src/main/java
    livereload:
      enabled: true
  zipkin:
    base-url: http://localhost:8090
  sleuth:
    sampler:
      percentage: 1
server:
  port: 8081
  context-path: /app01