#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    defaultZone: http://localhost:8888/eureka/
#  instance:
#    hostname: localhost
#spring:
# devtools:
#   restart:
#     enabled: true
#     additional-paths: eureka/src/main/java
logging:
  level: debug
server:
  port: 8888
#  context-path: /eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/