eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#spring:
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: eureka/src/main/java
server:
  port: 8083
  context-path: /app03
spring:
  zipkin:
    base-url: http://localhost:8090