eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  zipkin:
    base-url: http://localhost:8090
  devtools:
    restart:
      enabled: true
      additional-paths: eureka/src/main/java
server:
  port: 8084
  context-path: /app04